GEMINI_API_KEY = "AIzaSyBv_TSx8n8pYNbf09YglTFzXmSphPiWy-4"

[gsheets_1]
spreadsheet = "https://docs.google.com/spreadsheets/d/1pN7lbitNgDnXmV3u-9HoXl6N_UpAGvO5OfQhpvUKf6o"
worksheet = "<worksheet-gid-or-folder-id>"
type = "service_account"
project_id = "control-tower-454909"
private_key_id = "1408e569009e220991a81fab55411878f379a71f"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEv..."
client_email = "control-tower@control-tower-454909.iam.gserviceaccount.com"
client_id = "s114379109486042769915"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/control-tower%40control-tower-454909.iam.gserviceaccount.com"
universe_domain = "googleapis.com"